- name: Clone Personal Things
  hosts: localhost
  tasks:
  - name: Clone jira tickets
    git:
      repo: https://github.com/nic-avant/jira-tickets.git
      dest: "{{ lookup('env', 'HOME') }}/work/jira-tickets"
      clone: true
  - name: Clone MacOS MOTD
    git:
      repo: https://github.com/nic-avant/.macos-motd.git
      dest: "{{ lookup('env', 'HOME') }}/.macos-motd"
      clone: true
  - name: Clone dotfiles
    git:
      repo: https://github.com/pypeaday/dotfiles.git
      dest: "{{ lookup('env', 'HOME') }}/dotfiles"
      clone: true
